### ISSUE TITLE
Crash when pressing "send" on Android 4.4

### ISSUE THREAD

**Issue by azrdev** [vector-im/riot-android#1112]
My riot reproducibly crashes instantly when I press the send button. Syslog:
~~~
04-09 11:46:47.654 D/AndroidRuntime(12879): Shutting down VM
04-09 11:46:47.654 W/dalvikvm(12879): threadid=1: thread exiting with uncaught exception (group=0x41578ce0)
04-09 11:46:47.664 E/AndroidRuntime(12879): FATAL EXCEPTION: main
04-09 11:46:47.664 E/AndroidRuntime(12879): Process: im.vector.alpha, PID: 12879
04-09 11:46:47.664 E/AndroidRuntime(12879): java.lang.IllegalStateException: This API not supported on Android 4.3 and earlier
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at android.webkit.WebViewClassic.evaluateJavaScript(WebViewClassic.java:2674)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at android.webkit.WebView.evaluateJavascript(WebView.java:905)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at im.vector.util.VectorMarkdownParser.markdownToHtml(VectorMarkdownParser.java:110)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at im.vector.VectorApp.markdownToHtml(VectorApp.java:233)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at im.vector.activity.VectorRoomActivity.sendTextMessage(VectorRoomActivity.java:1477)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at im.vector.activity.VectorRoomActivity.access$1600(VectorRoomActivity.java:120)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at im.vector.activity.VectorRoomActivity$9.onClick(VectorRoomActivity.java:629)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at android.view.View.performClick(View.java:4445)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at android.view.View$PerformClick.run(View.java:18446)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at android.os.Handler.handleCallback(Handler.java:733)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at android.os.Looper.loop(Looper.java:136)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at android.app.ActivityThread.main(ActivityThread.java:5181)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at java.lang.reflect.Method.invoke(Method.java:515)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
04-09 11:46:47.664 E/AndroidRuntime(12879): 	at dalvik.system.NativeStart.main(Native Method)
04-09 11:46:47.674 W/ActivityManager(390):   Force finishing activity im.vector.alpha/im.vector.activity.VectorRoomActivity
04-09 11:46:48.184 W/ActivityManager(390): Activity pause timeout for ActivityRecord{41db3ae8 u0 im.vector.alpha/im.vector.activity.VectorRoomActivity t22 f}
04-09 11:46:49.314 I/Process (12879): Sending signal. PID: 12879 SIG: 9
04-09 11:46:49.354 I/ActivityManager(390): Process im.vector.alpha (pid 12879) has died.
04-09 11:46:49.354 I/WindowState(390): WIN DEATH: Window{41d3c3b0 u0 im.vector.alpha/im.vector.activity.VectorRoomActivity}
04-09 11:46:49.354 W/ActivityManager(390): Scheduling restart of crashed service im.vector.alpha/im.vector.services.EventStreamService in 1000ms
04-09 11:46:49.374 I/WindowState(390): WIN DEATH: Window{41d4a060 u0 im.vector.alpha/im.vector.activity.VectorHomeActivity}
04-09 11:46:49.394 V/Zygote  (13066): Switching descriptor 32 to /dev/null
04-09 11:46:49.394 V/Zygote  (13066): Switching descriptor 10 to /dev/null
04-09 11:46:49.414 I/ActivityManager(390): Start proc im.vector.alpha for activity im.vector.alpha/im.vector.activity.VectorHomeActivity: pid=13066 uid=10089 gids={50089, 3003, 1028, 1015, 1006}
~~~

Since this is a custom ROM this might be my fault, i.e. I deleted parts of the Android implementation which should be there, but at least the message about 4.3 on a 4.4 system seems strange.

**Comment by ylecollen** [comment]
It has been fixed on the develop branch by added a try/catch block.

https://github.com/vector-im/riot-android/blob/develop/vector/src/main/java/im/vector/util/VectorMarkdownParser.java#L132
