### ISSUE TITLE
Application crashed while scrolling back in the room history

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1294]
reported by @brycec:cobryce.com
https://github.com/matrix-org/riot-android-rageshakes/issues/261

**Comment by ylecollen** [comment]
hread: main, Activity:im.vector.activity.VectorRoomActivity, Exception: java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131689936, class org.matrix.androidsdk.view.AutoScrollDownListView) with Adapter(class im.vector.adapters.VectorMessagesAdapter)]
	at android.widget.ListView.layoutChildren(ListView.java:1618)
	at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4719)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:618)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6322)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by bmarty** [comment]
Not reported anymore, should be fixed now
