### ISSUE TITLE
Application crashes while swiping medias

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1296]
at java.util.ArrayList.get(ArrayList.java:411)
	at android.support.v4.view.ViewPager.getChildDrawingOrder(ViewPager.java:828)
	at android.view.View.populateAccessibilityNodeInfoDrawingOrderInParent(View.java:7040)
	at android.view.View.onInitializeAccessibilityNodeInfoInternal(View.java:6993)
	at android.view.ViewGroup.onInitializeAccessibilityNodeInfoInternal(ViewGroup.java:3069)
	at android.webkit.WebView.onInitializeAccessibilityNodeInfoInternal(WebView.java:2513)
	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6609)
	at org.chromium.content.browser.accessibility.BrowserAccessibilityManager$1.createAccessibilityNodeInfo(BrowserAccessibilityManager.java:1656)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:6565)
	at android.view.View.createAccessibilityNodeInfo(View.java:6553)
	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
	at android.view.View.onInitializeAccessibilityEventInternal(View.java:6505)
	at android.webkit.WebView.onInitializeAccessibilityEventInternal(WebView.java:2520)
	at android.view.View.onInitializeAccessibilityEvent(View.java:6493)
	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:6358)
	at android.view.View.sendAccessibilityEventUnchecked(View.java:6343)
	at android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:23679)
	at android.view.View$SendViewStateChangedAccessibilityEvent.runOrPost(View.java:23712)
	at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:9475)
	at android.view.View.onFocusChanged(View.java:6226)
	at android.webkit.WebView.onFocusChanged(WebView.java:2591)
	at android.view.View.clearFocusInternal(View.java:6130)
	at android.view.View.unFocus(View.java:6163)
	at android.view.ViewGroup.unFocus(ViewGroup.java:996)
	at android.view.ViewGroup.unFocus(ViewGroup.java:998)
	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:735)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4449)
	at android.view.ViewGroup.addView(ViewGroup.java:4258)
	at android.support.v4.view.ViewPager.addView(ViewPager.java:1505)
	at android.view.ViewGroup.addView(ViewGroup.java:4198)
	at im.vector.adapters.VectorMediasViewerAdapter.instantiateItem(VectorMediasViewerAdapter.java:405)
	at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1216)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
	at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:618)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by ylecollen** [comment]
Reported by @Obie:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/266

**Comment by ylecollen** [comment]
I don't reproduce it.

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/327
