### ISSUE TITLE
SSL handshake failed using own server with SSL v3 disabled

### ISSUE THREAD

**Issue by viktara** [vector-im/riot-android#1376]
This seems like a bug in 6.9.10 although I have not tried with other versions.

When using a custom matrix server where SSL v3 is disabled it seems riot still tries to use SSL v 3 but login fails with this error
![tmp_23946-img_20170626_0901051834105904](https://user-images.githubusercontent.com/1295145/27532239-7c9f28b2-5a57-11e7-82b2-eb6c30a5bf8c.jpg)

**Comment by pravi** [comment]
This link might be helpful https://stackoverflow.com/questions/26649389/how-to-disable-sslv3-in-android-for-httpsurlconnection#29946540

**Comment by ArchangeGabriel** [comment]
Hum, no issues here with an even more restricted setup server side.

This seems to be a Nexus 5, what OS/which version of it? TLS 1.1 and 1.2 where enabled by default starting with Android 5.0 AFAIK. So if your OS version is below that, you might not have anything above, hence the error.

**Comment by viktara** [comment]
I think the Nexus runs android 4.4 - it's my son's phone so I'll check that later - but seems like that may well be the culprit.

**Comment by ArchangeGabriel** [comment]
OK, then upgrading the OS should do it. For Nexus 5, versions up to 6.0.1 are available. ;)

**Comment by ArchangeGabriel** [comment]
(And even more if you consider alternative ROMs like OmniROM or LineageOS)

**Comment by pravi** [comment]
There were other users complaining too. I don't think LineageOS supports every phone model. As per the stackoverflow linked above, its a bug in Android, that can be worked around at the client side.

**Comment by pravi** [comment]
can't we use this lib so it works in Adroid < 4.4 https://guardianproject.info/code/netcipher/ ?

**Comment by ArchangeGabriel** [comment]
Oh, sorry, I’ve jumped from SSL 3 to TLS 1.1+ in my mind. And TLS 1.0 should be supported by Android 4.4 indeed.

Though if the bug is < 4.4 and not ≤ 4.4, this does not explain reported issue. Maybe TLS 1.0 is disabled too or it’s ≤ in fact.

Anyway, Android ≤ 4.4 will become an issue w.r.t. security quite soon, as TLS 1.0 is going away (in one year for PCI-DSS, but could happen before in case of new breach just like POODLE killed SSL v3).

Yes, Lineage OS does not support all smartphones. Even a lot of them in fact. But the people responsible here are hardware vendors, that don’t support their product very long… when they do at all! Educating people toward buying smartphones that keep being supported (either by the vendor — best case, very rare — or the community). Obviously they will still be some point at which upgrade won’t be possible because of missing hardware features. But for instance a Nexus 5 is a smartphone running very well under Lineage OS 14.1, a.k.a. Android 7.1. ;)

**Comment by AltNico** [comment]
I had the same problem, but with even newer phones (e.g. Android 7.0) failing with my server which had SSLv3 deactivated. In browsers my website worked, but in Riot I got this error and a toast saying "Handshake failed" on one device (Android 7.0) when entering my homeserver's URL on the registration screen:
```bash
10-08 09:31:53.493 26021 26021 E LoginActivity: Network Error: Handshake failed
10-08 09:31:53.493 26021 26021 E LoginActivity: javax.net.ssl.SSLHandshakeException: Handshake failed
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:444)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:302)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:270)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:162)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at org.matrix.androidsdk.RestClient$2.intercept(RestClient.java:169)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at org.matrix.androidsdk.RestClient$1.intercept(RestClient.java:157)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at java.lang.Thread.run(Thread.java:762)
10-08 09:31:53.493 26021 26021 E LoginActivity: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0xba5feb00: Failure in SSL library, usually a protocol error
10-08 09:31:53.493 26021 26021 E LoginActivity: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/s3_pkt.c:641 0xba82e1a0:0x00000001)
10-08 09:31:53.493 26021 26021 E LoginActivity: error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/s3_clnt.c:800 0xd5ea8b7b:0x00000000)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:364)
10-08 09:31:53.493 26021 26021 E LoginActivity: 	... 32 more
```

I had problems with registering on other devices, too, but I don't have any logs of them. Though, I guess it was the same error.

To come to my solution: Like I said, I had no SSLv3 on my server activated (and still don't have it yet). This is like my nginx configuration looked like:
```nginx
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
```
This configuration used to work in nearly all places I interacted with my server, but like I said above it did not on some devices.

I then used [Mozilla's SSL Configuration Generator](https://mozilla.github.io/server-side-tls/ssl-config-generator/) to generate a _Intermediate_ configuration, resulting in this:
```nginx
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
ssl_prefer_server_ciphers on;
```
Like you see, I still don't have SSLv3 enabled on my sever, but got a lot more ciphers now. The mentioned device's Riot is working with my homeserver now, I hope the other devices do that, too.

@viktara Maybe that's the problem with your custom homeserver, too. Regarding Mozilla, this setup supports Android devices down to version 2.3.

Related open issue: https://github.com/vector-im/riot-android/issues/2621

**Comment by r4dh4l** [comment]
Just wanted to add: I have this problem on (so far just) one single Android6 device after Upgrading to Synapse 0.99.0.

**Comment by reivilibre** [comment]
Just to note that I have also encountered this issue and the nginx configuration modification suggested in https://github.com/vector-im/riot-android/issues/1376#issuecomment-427761890 was successful at working around the problem.

**Comment by r4dh4l** [comment]
Nginx modification would be an option but it won't work for home servers where clients connect via synapse federation/server port (which may be the case in some dynamic DNS setups for "real" home servers (so with just one IP) where port 443 is already in use).
