### ISSUE TITLE
crashed after joining (and leaving) room (irc bridge)

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1524]
reported by @dh2048:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/800

**Comment by ylecollen** [comment]
Thread: main, Activity:im.vector.activity.VectorRoomActivity, Exception: java.lang.IllegalStateException: eglMakeCurrent failed EGL_BAD_ALLOC
at android.view.HardwareRenderer$GlRenderer.createSurface(HardwareRenderer.java:1264)
at android.view.HardwareRenderer$GlRenderer.createEglSurface(HardwareRenderer.java:1156)
at android.view.HardwareRenderer$GlRenderer.initialize(HardwareRenderer.java:980)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1059)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5760)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:835)
at android.view.Choreographer.doCallbacks(Choreographer.java:626)
at android.view.Choreographer.doFrame(Choreographer.java:590)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:821)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5390)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)

**Comment by ylecollen** [comment]
i don't see the relationship between the "eglMakeCurrent failed EGL_BAD_ALLOC" and the join/leave action.

it looks like the call management issue.

**Comment by ylecollen** [comment]
Thread: main, Activity:im.vector.activity.VectorRoomActivity, Exception: java.lang.IllegalStateException: eglMakeCurrent failed EGL_BAD_ALLOC
at android.view.HardwareRenderer$GlRenderer.createSurface(HardwareRenderer.java:1264)
at android.view.HardwareRenderer$GlRenderer.createEglSurface(HardwareRenderer.java:1156)
at android.view.HardwareRenderer$GlRenderer.initialize(HardwareRenderer.java:980)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1059)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5760)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:835)
at android.view.Choreographer.doCallbacks(Choreographer.java:626)
at android.view.Choreographer.doFrame(Choreographer.java:590)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:821)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5390)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)

**Comment by ylecollen** [comment]
https://stackoverflow.com/questions/19668242/problems-with-passing-variable-via-intent-between-activities

Out of memory ?
