### ISSUE TITLE
cannot login with large account

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1530]
reported by @travis:t2l.io
https://github.com/matrix-org/riot-android-rageshakes/issues/831

the application max memory size is about 512MB.

usedSize   503 MB
freeSize   8 MB
totalSize   512 MB
Thread: MXFileStoreBackgroundThread_@travis:t2l.io, Activity:im.vector.activity.SplashActivity, Exception: java.lang.OutOfMemoryError: Failed to allocate a 20 byte allocation with 8475736 free bytes and 8MB until OOM; failed due to fragmentation (required continguous free 4096 bytes for a new buffer where largest contiguous free 0 bytes)
	at org.matrix.androidsdk.data.store.MXFileStore$3$1.run(MXFileStore.java:963)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ylecollen** [comment]
we need to find a way to reduce memory usage.

**Comment by ylecollen** [comment]
i also suspect that the initial sync response is huge.

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/835

**Comment by noxarivis** [comment]
@ylevollen

you are a true Sherlock
https://github.com/vector-im/riot-android/issues/1496

**Comment by ylecollen** [comment]
Should help

-> https://github.com/matrix-org/matrix-android-sdk/commit/a8168a49608cb1ce113a032269f5d4e556676bc8
-> https://github.com/matrix-org/matrix-android-sdk/commit/da571696ce16075f3de8a3f9eb076c3eb6620bb8

**Comment by noxarivis** [comment]
@ylecollen
im glad that ur back


it was a tight end
