### ISSUE TITLE
I touched the notification saying I got an invitation to join a room. didn't hit any of the buttons (reject, join)

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1549]
reported by @Lexi:matrix.org
I touched the notification saying I got an invitation to join a room. didn't hit any of the buttons (reject, join)
https://github.com/matrix-org/riot-android-rageshakes/issues/917

**Comment by ylecollen** [comment]
Riot.im Build : 70000
Riot.im Version : 0.7.00 (GooglePlay-faf0015ca-2017-08-01 09:43:34 +0200)
SDK Version : 0.8.00 (adb05342b-2017-07-31 17:43:54 +0200)
Phone : MyTouch 4G Slide (356011 4.2.2 REL)
Memory statuses 
usedSize   12 MB
freeSize   5 MB
totalSize   17 MB
Thread: main, Exception: java.lang.IllegalStateException: Could not create an EGL context. eglCreateContext failed with error: EGL_SUCCESS
	at android.view.HardwareRenderer$GlRenderer.createContext(HardwareRenderer.java:997)
	at android.view.HardwareRenderer$GlRenderer.initializeEgl(HardwareRenderer.java:866)
	at android.view.HardwareRenderer$GlRenderer.initialize(HardwareRenderer.java:786)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1502)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
	at android.view.Choreographer.doFrame(Choreographer.java:532)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5227)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
	at dalvik.system.NativeStart.main(Native Method)
