### ISSUE TITLE
Crash in preferenceGroup

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1580]
Reported by @v7r:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/989
crash while typing in people search

**Comment by ylecollen** [comment]
Thread: main, Activity:im.vector.activity.VectorHomeActivity, Exception: java.lang.IndexOutOfBoundsException: Invalid index 21, size is 21
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at android.preference.PreferenceGroup.getPreference(PreferenceGroup.java:123)
	at android.preference.PreferenceGroupAdapter.flattenPreferenceGroup(PreferenceGroupAdapter.java:163)
	at android.preference.PreferenceGroupAdapter.syncMyPreferences(PreferenceGroupAdapter.java:146)
	at android.preference.PreferenceGroupAdapter.access$100(PreferenceGroupAdapter.java:53)
	at android.preference.PreferenceGroupAdapter$1.run(PreferenceGroupAdapter.java:92)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5441)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by bmarty** [comment]
Close rage shake 989 is closed
