### ISSUE TITLE
When opening a room, the application falls into an error and closes 

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1595]
reported by @rassadin_im:im.magnit.ru
https://github.com/matrix-org/riot-android-rageshakes/issues/1014

**Comment by ylecollen** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String[] com.mediatek.common.util.IWebProtocolNames.getWebProtocolNames()' on a null object reference
	at android.text.util.Linkify.addLinks(Linkify.java:226)
	at android.widget.TextView.setText(TextView.java:4018)
	at android.widget.TextView.setText(TextView.java:3940)
	at android.widget.TextView.<init>(TextView.java:1339)
	at android.widget.TextView.<init>(TextView.java:651)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:729)

**Comment by ylecollen** [comment]
It seems being a ROM issue on Redmi Note 3.

**Comment by wuzhenmin** [comment]
fix？
