### ISSUE TITLE
too many AsyncTask 

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1642]
reported by @firouziyan:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/1188

**Comment by ylecollen** [comment]
Thread: main, Activity:im.vector.activity.VectorRoomDetailsActivity, Exception: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$SerialExecutor$1@5cda533 rejected from java.util.concurrent.ThreadPoolExecutor@95e1179[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 345]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2049)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:814)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1360)
	at android.os.AsyncTask$SerialExecutor.scheduleNext(AsyncTask.java:256)
	at android.os.AsyncTask$SerialExecutor.execute(AsyncTask.java:250)
	at android.app.ActivityThread.sendOPInsightLog(ActivityThread.java:6329)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3857)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3834)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3808)
	at android.app.ActivityThread.-wrap16(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
