### ISSUE TITLE
failed to initialise the webrtc instance

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1842]
12-29 14:26:53.987  6279  6279 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setStream(Lorg/webrtc/MediaStream;)V in class Lcom/oney/WebRTCModule/WebRTCView; or its super classes (declaration of 'com.oney.WebRTCModule.WebRTCView' appears in base.apk)
12-29 14:26:53.987  6279  6279 E AndroidRuntime: 	at org.matrix.androidsdk.call.MXWebRtcCall.createLocalStream(MXWebRtcCall.java:553)
12-29 14:26:53.987  6279  6279 E AndroidRuntime: 	at org.matrix.androidsdk.call.MXWebRtcCall.access$1300(MXWebRtcCall.java:62)
12-29 14:26:53.987  6279  6279 E AndroidRuntime: 	at org.matrix.androidsdk.call.MXWebRtcCall$7.run(MXWebRtcCall.java:1084)
12-29 14:26:53.987  6279  6279 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
12-29 14:26:53.987  6279  6279 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-29 14:26:53.987  6279  6279 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-29 14:26:53.987  6279  6279 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6171)
12-29 14:26:53.987  6279  6279 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 14:26:53.987  6279  6279 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
12-29 14:26:53.987  6279  6279 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
12-29 14:27:22.680  8484  8484 E AndroidRuntime: FATAL EXCEPTION: main
12-29 14:27:22.680  8484  8484 E AndroidRuntime: Process: im.vector.alpha, PID: 8484
12-29 14:27:22.680  8484  8484 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setStream(Lorg/webrtc/MediaStream;)V in class Lcom/oney/WebRTCModule/WebRTCView; or its super classes (declaration of 'com.oney.WebRTCModule.WebRTCView' appears in base.apk)
12-29 14:27:22.680  8484  8484 E AndroidRuntime: 	at org.matrix.androidsdk.call.MXWebRtcCall.createLocalStream(MXWebRtcCall.java:553)
12-29 14:27:22.680  8484  8484 E AndroidRuntime: 	at org.matrix.androidsdk.call.MXWebRtcCall.access$1300(MXWebRtcCall.java:62)
12-29 14:27:22.680  8484  8484 E AndroidRuntime: 	at org.matrix.androidsdk.call.MXWebRtcCall$7.run(MXWebRtcCall.java:1084)
12-29 14:27:22.680  8484  8484 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
12-29 14:27:22.680  8484  8484 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-29 14:27:22.680  8484  8484 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-29 14:27:22.680  8484  8484 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6171)
12-29 14:27:22.680  8484  8484 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 14:27:22.680  8484  8484 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
12-29 14:27:22.680  8484  8484 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by ylecollen** [comment]
https://github.com/matrix-org/matrix-android-sdk/commit/3a04797f3104d0bb61d1660476693123e2330107
