### ISSUE TITLE
Riot doesn't load

### ISSUE THREAD

**Issue by Serkan-devel** [vector-im/riot-android#2353]
Riot only stays at the loading screen after logging in and crashes after a while

Device: Samsung gt-i9100

Android: 7.1.2 (LineageOS 14.1)

Logcat (I've changed the Wifi-name to something else):
[riot_logcat1.txt](https://github.com/vector-im/riot-android/files/2086950/riot_logcat1.txt)

**Comment by bmarty** [comment]
```
06-09 12:02:29.076 15258 15258 E AndroidRuntime: FATAL EXCEPTION: main
06-09 12:02:29.076 15258 15258 E AndroidRuntime: Process: im.vector.alpha, PID: 15258
06-09 12:02:29.076 15258 15258 E AndroidRuntime: java.lang.ClassCastException: java.lang.OutOfMemoryError cannot be cast to java.lang.Exception
06-09 12:02:29.076 15258 15258 E AndroidRuntime: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.onFailure(RestAdapterCallback.java:148)
06-09 12:02:29.076 15258 15258 E AndroidRuntime: 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$2.run(ExecutorCallAdapterFactory.java:79)
06-09 12:02:29.076 15258 15258 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
06-09 12:02:29.076 15258 15258 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-09 12:02:29.076 15258 15258 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-09 12:02:29.076 15258 15258 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
06-09 12:02:29.076 15258 15258 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-09 12:02:29.076 15258 15258 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-09 12:02:29.076 15258 15258 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-09 12:02:29.121  2285  7856 W ActivityManager:   Force finishing activity im.vector.alpha/im.vector.activity.SplashActivity
```

**Comment by uhoreg** [comment]
I think I had a similar issue, and I worked around it by temporarily leaving some large rooms (using Riot desktop), starting Riot Android, and then re-joining the rooms after Riot Android started.

**Comment by Serkan-devel** [comment]
Does it need to be done after every restart?

**Comment by uhoreg** [comment]
I don't need to be done on every restart.  Only when it needs to do an initial sync (which is when I do a clear-cache-and-reload, or the one time when Riot for some reason lost its cache).

**Comment by Serkan-devel** [comment]
Can the loading problem be fixed, so riot can run on lower powered devices? The webpage doesn't load on my phone either

**Comment by Serkan-devel** [comment]
Actually, it loads for me now after leaving some channels as described above. Sorry for reporting late
