### ISSUE TITLE
FATAL EXCEPTION on file save

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [vector-im/riot-android#2573]
I press on the csv file on the unencrypted room and it successfully saves.
But riot stops:
logcat:

```
09-03 21:48:56.677   508   537 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]
09-03 21:48:56.679   508   537 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 0]
09-03 21:48:56.680   508   537 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]
09-03 21:48:56.680   508   537 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 0]
09-03 21:48:56.765  2177  7815 D NuPlayerDriver: NuPlayerDriver(0xe8a18200) created, clientPid(3079)
09-03 21:48:56.772  2177 14166 D GenericSource: FileSource remote
09-03 21:48:56.781  2177 14165 D NuPlayerDriver: notifyListener_l(0xe8a18200), (1, 0, 0, -1), loop setting(0, 0)
09-03 21:48:56.789  2474  4184 I MediaFocusControl: requestAudioFocus() from uid/pid 10031/3079 clientId=android.media.AudioManager@d186421 callingPack=com.android.systemui req=3 flags=0x0 sdk=27
09-03 21:48:56.821 13911 13911 D AndroidRuntime: Shutting down VM
09-03 21:48:56.822 13911 13911 E AndroidRuntime: FATAL EXCEPTION: main
09-03 21:48:56.822 13911 13911 E AndroidRuntime: Process: im.vector.alpha, PID: 13911
09-03 21:48:56.822 13911 13911 E AndroidRuntime: android.os.FileUriExposedException: file:///storage/emulated/0/Download/LoyaltyCardKeychain(3).csv exposed beyond app through Intent.getData()
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.net.Uri.checkFileUriExposed(Uri.java:2356)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:9881)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:9835)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4487)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4445)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4806)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4774)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at im.vector.activity.MXCActionBarActivity.startActivity(MXCActionBarActivity.java:90)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at im.vector.util.ExternalApplicationsUtilKt.openMedia(ExternalApplicationsUtil.kt:238)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at im.vector.fragments.VectorMessageListFragment$19$1.onSuccess(VectorMessageListFragment.java:854)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at im.vector.fragments.VectorMessageListFragment$19$1.onSuccess(VectorMessageListFragment.java:847)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at im.vector.activity.CommonActivityUtils$12.onSuccess(CommonActivityUtils.java:1193)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at im.vector.activity.CommonActivityUtils$12.onSuccess(CommonActivityUtils.java:1178)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at im.vector.activity.CommonActivityUtils$10.onPostExecute(CommonActivityUtils.java:1138)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at im.vector.activity.CommonActivityUtils$10.onPostExecute(CommonActivityUtils.java:1051)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
09-03 21:48:56.822 13911 13911 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
09-03 21:48:56.826  2474  4184 W ActivityManager:   Force finishing activity im.vector.alpha/im.vector.activity.VectorRoomActivity
09-03 21:48:56.838  2474  2529 I ActivityManager: Showing crash dialog for package im.vector.alpha u0

```

**Comment by digititus** [comment]
I have similar issue with .pdf .docx and .xlsx files. Click and Riot crashes. Click and hold and I'm given the option to save.

**Comment by dkanada** [comment]
I had the same issue in another app after I got an Oreo phone. Not sure why it doesn't trigger for images or videos but I found a possible solution below.

https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed#38858040

**Comment by bmarty** [comment]
The exception was before caught (see https://github.com/vector-im/riot-android/commit/55593b7d3a2d6b4031406d3469a2b3ead8a2da99), but the sharing was not working then

We have to fix this before the next release.

**Comment by bmarty** [comment]
Ok, fixed
