### ISSUE TITLE
Android 8: crash on device Boot

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2615]
Reported by RS: The app fails to start on boot but succeeds in starting manually afterwards.

https://github.com/matrix-org/riot-android-rageshakes/issues/3101

```
09-20 15:23:26.932  2421  2421 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver im.vector.receiver.VectorBootReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=im.vector.alpha/im.vector.services.EventStreamService (has extras) }: app is in background uid UidRecord{b6194b6 u0a123 RCVR idle change:uncached procs:1 seq(0,0,0)}
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=im.vector.alpha/im.vector.services.EventStreamService (has extras) }: app is in background uid UidRecord{b6194b6 u0a123 RCVR idle change:uncached procs:1 seq(0,0,0)}
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1477)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at im.vector.activity.CommonActivityUtils.startEventStreamService(CommonActivityUtils.java:598)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at im.vector.receiver.VectorBootReceiver.onReceive(VectorBootReceiver.java:39)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
09-20 15:23:26.932  2421  2421 E AndroidRuntime: 	... 8 more
```

**Comment by bmarty** [comment]
Done
