### ISSUE TITLE
Crash when change visibility room on hs

### ISSUE THREAD

**Issue by tim06** [vector-im/riot-android#2679]
Xiaomi Redmi Note 4
Riot version 0.8.18
Android 6.0

Click on checkbox in room preferences causes crash

`java.lang.IllegalArgumentException: No Retrofit annotation found. (parameter #2)
        for method RoomsApi.setRoomDirectoryVisibility
        at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:755)
        at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:746)
        at retrofit2.ServiceMethod$Builder.parameterError(ServiceMethod.java:764)
        at retrofit2.ServiceMethod$Builder.parseParameter(ServiceMethod.java:354)
        at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:207)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at $Proxy3.setRoomDirectoryVisibility(Unknown Source)
        at org.matrix.androidsdk.rest.client.RoomsRestClient.updateDirectoryVisibility(RoomsRestClient.java:555)
        at org.matrix.androidsdk.data.Room.updateDirectoryVisibility(Room.java:1066)
        at im.vector.fragments.VectorRoomSettingsFragment.onRoomDirectoryVisibilityPreferenceChanged(VectorRoomSettingsFragment.java:1081)
        at im.vector.fragments.VectorRoomSettingsFragment.onSharedPreferenceChanged(VectorRoomSettingsFragment.java:928)
`

**Comment by bmarty** [comment]
Hi @tim06 ,
thanks for reporting. It's fixed on the next release
Benoît
