### ISSUE TITLE
conference call cant work

### ISSUE THREAD

**Issue by wjhtinger** [vector-im/riot-android#2680]
cant lounch conference all, and below is log:
    Process: im.vector.alpha, PID: 17510
    java.lang.RuntimeException: Unable to start activity ComponentInfo{im.vector.alpha/im.vector.activity.JitsiCallActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.action.MANAGE_OVERLAY_PERMISSION dat=package:im.vector.alpha }
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2536)
        at android.app.ActivityThread.access$900(ActivityThread.java:159)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5500)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.action.MANAGE_OVERLAY_PERMISSION dat=package:im.vector.alpha }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
        at android.app.Activity.startActivityForResult(Activity.java:3970)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:3931)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
        at im.vector.activity.JitsiCallActivity.initUiAndData(JitsiCallActivity.java:164)
        at im.vector.activity.VectorAppCompatActivity.onCreate(VectorAppCompatActivity.kt:95)
        at android.app.Activity.performCreate(Activity.java:6292)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2536) 
        at android.app.ActivityThread.access$900(ActivityThread.java:159) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5500) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by bmarty** [comment]
Done
