### ISSUE TITLE
Crash when start group call

### ISSUE THREAD

**Issue by tim06** [vector-im/riot-android#2696]
Android 6.0

````
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules

java.lang.IllegalArgumentException: unexpected url: lang/main-ru.json
        at okhttp3.Request$Builder.url(Request.java:143)
        at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:171)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:207)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
        at java.lang.Thread.run(Thread.java:818)
````

**Comment by tim06** [comment]
I changed the language and everything was fine...
