### ISSUE TITLE
zoom-out on image causes crash

### ISSUE THREAD

**Issue by yyportne** [vector-im/riot-android#2786]
Zoom-out on image causes crash in riot version 0.8.20 (G-b159).

Steps to reproduce:
[1] Open image (image is displayed to fit in the display boundaries)
[2] Try to zoom out
[3] Repeat [2] until crash

I've noticed that in step [2] the image is sometimes displayed a few pixels smaller than the device boundaries before the crash occurs.

**Comment by bmarty** [comment]
Thanks for reporting,

Here is the backstack of the crash
```
    java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:2519)
        at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2066)
        at im.vector.view.RiotViewPager.onInterceptTouchEvent(RiotViewPager.java:44)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2696)
```

**Comment by chresan** [comment]
Thank you for addressing this issue.
