### ISSUE TITLE
Firebase Token retrieval fails silently in some cases

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riot-android#2846]
In some cases Firebase token retrieval fails silently -> effect is that push will not work

This was detected thanks to a rageshake - >Crashes during notification troubleshooting (during the Firebase token part) 

```
01-08 16:22:53.155Z 2 E/FcmHelper: ## ensureFcmTokenIsRetrieved() : failed Default FirebaseApp is not initialized in this process im.vector.alpha. Make sure to call FirebaseApp.initializeApp(Context) first.
01-08 16:22:53.157Z java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process im.vector.alpha. Make sure to call FirebaseApp.initializeApp(Context) first.
	at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.2:240)
	at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source:1)
	at im.vector.push.fcm.FcmHelper.ensureFcmTokenIsRetrieved(FcmHelper.java:86)
	at im.vector.activity.LoginActivity.initUiAndData(LoginActivity.java:376)
	at im.vector.activity.VectorAppCompatActivity.onCreate(VectorAppCompatActivity.kt:99)
	at android.app.Activity.performCreate(Activity.java:7036)
	at android.app.Activity.performCreate(Activity.java:7027)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

https://github.com/matrix-org/riot-android-rageshakes/issues/3526

**Comment by BillCarsonFr** [comment]
Additional info here:
https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseApp

`For a vast majority of apps, FirebaseInitProvider will handle the initialization of Firebase for the default project that it's configured to work with, via the data contained in the app's google-services.json file. 
`

`In the event that an app requires access to another Firebase project in addition to the default project, initializeApp(Context, FirebaseOptions, String) must be used to create that relationship programmatically.`
