### ISSUE TITLE
BugScreen report crash on Android P

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2876]
Go to Bug report screen.
Click on the edit text, or rotate screen, or click on "Send screenshot" checlbox.
Application crash:
```
    Thread: main, Activity:im.vector.activity.BugReportActivity, Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@c055e27
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:70)
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:101)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
        at android.widget.ImageView.onDraw(ImageView.java:1360)
```

Can't see where it can come from, that's why I open an issue.

Not crashing on API 18.

**Comment by bmarty** [comment]
"Do not keep Activity" is set to On
