### ISSUE TITLE
RageShake: crash entering the settings

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2893]
https://github.com/matrix-org/riot-android-rageshakes/issues/3579

```
--------- beginning of crash
01-22 22:00:49.588  3449  3449 E AndroidRuntime: FATAL EXCEPTION: main
01-22 22:00:49.588  3449  3449 E AndroidRuntime: Process: im.vector.alpha, PID: 3449
01-22 22:00:49.588  3449  3449 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {im.vector.alpha/im.vector.activity.VectorSettingsActivity}: java.lang.IllegalStateException: it.findDefaultRule(mPush…ResourceId[resourceText]) must not be null
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3805)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3845)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3065)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: Caused by: java.lang.IllegalStateException: it.findDefaultRule(mPush…ResourceId[resourceText]) must not be null
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at im.vector.fragments.VectorSettingsPreferencesFragment.refreshDisplay(VectorSettingsPreferencesFragment.kt:1017)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at im.vector.fragments.VectorSettingsPreferencesFragment.onResume(VectorSettingsPreferencesFragment.kt:908)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3212)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:217)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7464)
01-22 22:00:49.588  3449  3449 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3780)
```

**Comment by bmarty** [comment]
Fix implemented
