### ISSUE TITLE
Blank room in Android 4.x

### ISSUE THREAD

**Issue by hrj** [vector-im/riot-android#2917]
When viewing a room in Android 4.x device, the layout inflater throws the following exception:

```
E/AutoScrollDownListView( 1936): ## layoutChildren() failed Binary XML file line #5: Error inflating class <unknown>
E/AutoScrollDownListView( 1936): android.view.InflateException: Binary XML file line #5: Error inflating class <unknown>
E/AutoScrollDownListView( 1936): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/AutoScrollDownListView( 1936): 	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
E/AutoScrollDownListView( 1936): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
E/AutoScrollDownListView( 1936): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
E/AutoScrollDownListView( 1936): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AutoScrollDownListView( 1936): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:814)
E/AutoScrollDownListView( 1936): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
E/AutoScrollDownListView( 1936): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AutoScrollDownListView( 1936): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AutoScrollDownListView( 1936): 	at im.vector.adapters.VectorMessagesAdapter.getTextView(VectorMessagesAdapter.java:1205)
E/AutoScrollDownListView( 1936): 	at im.vector.adapters.VectorMessagesAdapter.getView(VectorMessagesAdapter.java:762)
E/AutoScrollDownListView( 1936): 	at android.widget.AbsListView.obtainView(AbsListView.java:2177)
E/AutoScrollDownListView( 1936): 	at android.widget.ListView.makeAndAddView(ListView.java:1840)
E/AutoScrollDownListView( 1936): 	at android.widget.ListView.fillSpecific(ListView.java:1321)
E/AutoScrollDownListView( 1936): 	at android.widget.ListView.layoutChildren(ListView.java:1645)
E/AutoScrollDownListView( 1936): 	at org.matrix.androidsdk.view.AutoScrollDownListView.layoutChildren(AutoScrollDownListView.java:77)
E/AutoScrollDownListView( 1936): 	at android.widget.AbsListView.onLayout(AbsListView.java:2012)
E/AutoScrollDownListView( 1936): 	at android.view.View.layout(View.java:14289)
E/AutoScrollDownListView( 1936): 	at android.view.ViewGroup.layout(ViewGroup.java:4562)
E/AutoScrollDownListView( 1936): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AutoScrollDownListView( 1936): 	at android.view.View.layout(View.java:14289)
E/AutoScrollDownListView( 1936): 	at android.view.ViewGroup.layout(ViewGroup.java:4562)
E/AutoScrollDownListView( 1936): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AutoScrollDownListView( 1936): 	at android.view.View.layout(View.java:14289)
E/AutoScrollDownListView( 1936): 	at android.view.ViewGroup.layout(ViewGroup.java:4562)
E/AutoScrollDownListView( 1936): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
E/AutoScrollDownListView( 1936): 	at android.view.View.layout(View.java:14289)
E/AutoScrollDownListView( 1936): 	at android.view.ViewGroup.layout(ViewGroup.java:4562)
E/AutoScrollDownListView( 1936): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
E/AutoScrollDownListView( 1936): 	at android.view.View.layout(View.java:14289)
E/AutoScrollDownListView( 1936): 	at android.view.ViewGroup.layout(ViewGroup.java:4562)
E/AutoScrollDownListView( 1936): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AutoScrollDownListView( 1936): 	at android.view.View.layout(View.java:14289)
E/AutoScrollDownListView( 1936): 	at android.view.ViewGroup.layout(ViewGroup.java:4562)
E/AutoScrollDownListView( 1936): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
E/AutoScrollDownListView( 1936): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
E/AutoScrollDownListView( 1936): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
E/AutoScrollDownListView( 1936): 	at android.view.View.layout(View.java:14289)
E/AutoScrollDownListView( 1936): 	at android.view.ViewGroup.layout(ViewGroup.java:4562)
E/AutoScrollDownListView( 1936): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AutoScrollDownListView( 1936): 	at android.view.View.layout(View.java:14289)
E/AutoScrollDownListView( 1936): 	at android.view.ViewGroup.layout(ViewGroup.java:4562)
E/AutoScrollDownListView( 1936): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
E/AutoScrollDownListView( 1936): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
E/AutoScrollDownListView( 1936): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
E/AutoScrollDownListView( 1936): 	at android.view.View.layout(View.java:14289)
E/AutoScrollDownListView( 1936): 	at android.view.ViewGroup.layout(ViewGroup.java:4562)
E/AutoScrollDownListView( 1936): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AutoScrollDownListView( 1936): 	at android.view.View.layout(View.java:14289)
E/AutoScrollDownListView( 1936): 	at android.view.ViewGroup.layout(ViewGroup.java:4562)
E/AutoScrollDownListView( 1936): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1976)
E/AutoScrollDownListView( 1936): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1730)
E/AutoScrollDownListView( 1936): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
E/AutoScrollDownListView( 1936): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
E/AutoScrollDownListView( 1936): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
E/AutoScrollDownListView( 1936): 	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
E/AutoScrollDownListView( 1936): 	at android.view.Choreographer.doFrame(Choreographer.java:532)
E/AutoScrollDownListView( 1936): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
E/AutoScrollDownListView( 1936): 	at android.os.Handler.handleCallback(Handler.java:730)
E/AutoScrollDownListView( 1936): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AutoScrollDownListView( 1936): 	at android.os.Looper.loop(Looper.java:137)
E/AutoScrollDownListView( 1936): 	at android.app.ActivityThread.main(ActivityThr
```

This doesn't crash the activity, but the room appears blank.

The problem seems to be that `?android:colorAccent` is not defined in older Android versions. As a workaround, this works:

```
--- a/vector/src/main/res/values/theme_dark.xml
+++ b/vector/src/main/res/values/theme_dark.xml
@@ -45,7 +45,7 @@
         <item name="vctr_highlighted_message_text_color">@color/vector_fuchsia_color</item>
         <item name="vctr_highlighted_searched_message_text_color">@color/primary_color_light</item>
         <item name="vctr_search_mode_room_name_text_color">#CCC3C3C3</item>
-        <item name="vctr_unread_marker_line_color">?android:colorAccent</item>
+        <item name="vctr_unread_marker_line_color">?android:textColorSecondary</item>
         <item name="vctr_markdown_block_background_color">@android:color/black</item>
         <item name="vctr_room_activity_divider_color">#565656</item>
 
diff --git a/vector/src/main/res/values/theme_light.xml b/vector/src/main/res/values/theme_light.xml
index 27698e2..b89ba52 100644
--- a/vector/src/main/res/values/theme_light.xml
+++ b/vector/src/main/res/values/theme_light.xml
@@ -45,7 +45,7 @@
         <item name="vctr_highlighted_message_text_color">@color/vector_fuchsia_color</item>
         <item name="vctr_highlighted_searched_message_text_color">@color/primary_color_light</item>
         <item name="vctr_search_mode_room_name_text_color">#333C3C3C</item>
-        <item name="vctr_unread_marker_line_color">?android:colorAccent</item>
+        <item name="vctr_unread_marker_line_color">?android:textColorSecondary</item>
         <item name="vctr_markdown_block_background_color">#FFEEEEEE</item>
         <item name="vctr_room_activity_divider_color">#FFF2F2F2</item>
```

I tried solving this the correct way, but got sucked into a vortex (update Kotlin, update Gradle, update app compat libraries, etc), and finally gave up on that.

**Comment by bmarty** [comment]
Thanks for reporting, and for the suggestion. It's fixed
