### ISSUE TITLE
Riot 0.9.2 breaks on servers using self-signed certificates

### ISSUE THREAD

**Issue by tqbunny** [vector-im/riot-android#3221]
Receiving messages and attachments works fine. Sending messages hangs, and things such as accessing the application settings result in a toast for exception logging with the message "Trust anchor for certification path not found".

Expected behavior: 0.9.1 behavior where the application asks when trusting an user certificate, making servers with self-signed certificates work properly again.

**Comment by mehturt** [comment]
I can confirm this behavior.

**Comment by mehturt** [comment]
For me this problem persists with 0.9.3 as well

**Comment by tqbunny** [comment]
The workaround for now seems to stay on 0.9.1. It doesn't seem like the developers seem interested in fixing Riot Android issues. RiotX faces the same issue.

**Comment by mehturt** [comment]
Yes but I don't know how to go back to 0.9.1 (using Play Store).

**Comment by tqbunny** [comment]
As the F-Droid application has not been updated since 0.8.28a (2019-04-26), it is possible that you might have to build it yourself from the 0.9.1 source, unless you can find some APK. Reinstalling the application might be necessary.

**Comment by manuroe** [comment]
Sorry for this regression which was not intentional. 0.9.2 was more a maintenance release.
In part of this maintenance, libs that Riot uses have been updated. The issue is probably due to a newer version of the okHttp library.

Since Let's Encrypt is out, self-signed certificate support is no more the priority of the core team but any PR that solves it will be highly appreciated.

Meanwhile, you can find an apk on our CI at https://buildkite.com/matrix-dot-org/riot-android/builds/35#c3bbcafe-2139-4f9c-85a8-a2dda72cc870 (in the artifacts tab) which is the closest to 0.9.1 I found.

**Comment by tqbunny** [comment]
Thank you for replying.

Let's Encrypt is irrelevant and unusable for local, intranet and non domain-based Matrix servers. It is a shame that it is no longer a priority.

I cannot confirm the issue is due to okHttp specifically, but here is the stacktrace.

```
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: ## start failed : java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at org.matrix.androidsdk.crypto.rest.ParentRestClient$1.intercept(ParentRestClient.java:87)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at java.lang.Thread.run(Thread.java:764)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:739)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:612)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:499)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:422)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:343)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:203)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:607)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	... 26 more
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
07-25 19:19:08.025 23779 23779 E MXCryptoImpl: 	... 37 more
```

I believe the issue comes from newer versions not using a custom TrustManager. It seems that the okHttp3 client would require a custom SslSocketFactory. I am however unable to implement this, as my environment is not fit for Android development.

**Comment by mehturt** [comment]
Actually, my server is using LetsEncrypt certificate.. does it mean I need to raise a different bug?

**Comment by tqbunny** [comment]
If Let's Encrypt is not installed as a trusted authority on your device, it is likely the same issue.

**Comment by mehturt** [comment]
I don't get why this change is not reverted immediately in Play Store until it's fixed and properly tested..

**Comment by darkoppressor** [comment]
I recently started experiencing this as well, but like mehturt I am using LetsEncrypt and not a self-signed cert on my homeserver. Riot Web still connects and works fine with my homeserver, but Riot Android does not.

**Comment by darkoppressor** [comment]
Ok, I was able to fix this for myself. As I said, I'm using a LetsEncrypt cert. My problem was actually caused by my server being incorrectly configured. I'm using Apache, and my cert file is the fullchain.pem file. I had configured it as the cert file in Apache but not the cert chain file. mehturt, is it possible this is your problem too? I used https://www.digicert.com/help/ to detect my configuration problem.

**Comment by mehturt** [comment]
@darkoppressor how exactly did you diagnose this problem? I run the tool on the digicert.com web page, but I get all greens..

**Comment by mehturt** [comment]
Yes, I get it now. Indeed I was using the cert file instead of fullchain.pem.. even though this is described in the synapse's configuration comments :( So the problem is resolved for me as well.

**Comment by darkoppressor** [comment]
Awesome! So we didn't learn anything about the actual issue here but at least this might be helpful to anyone else with this seemingly related problem.

**Comment by fti7** [comment]
Same Issue here. But the own Root CA is imported on the device. An normal Browser doesnt show any Error Messages :-(

And it only appears when i go to the Settings Menu... very Strange
