### ISSUE TITLE
Crash: SAS / UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riot-android#3240]
https://github.com/matrix-org/riot-android-rageshakes/issues/6417

Caused by: kotlin.UninitializedPropertyAccessException: lateinit property session has not been initialized
at im.vector.fragments.verification.SasVerificationViewModel.onCleared(SasVerificationViewModel.kt:151)
at android.arch.lifecycle.ViewModelStore.clear(ViewModelStore.java:56)

**Comment by BillCarsonFr** [comment]
--> check for initialisation?
if (::session.isInitialized) { .. }
