### ISSUE TITLE
Hangs after entering credentials

### ISSUE THREAD

**Issue by logic** [vector-im/riot-android#3416]
When I try to connect to my homeserver via the riot android client (I've tried this with both the play store and f-droid versions), after entering credentials and having a new device created on the server, it hangs at the "riot.im" throbber splash screen forever, and never successfully syncs. `adb logcat` shows me the following, repeated (at what I assume is the retry interval) forever:

```
01-20 17:10:20.364 32535 32535 E ErrorListener: org.matrix.androidsdk.core.model.HttpException
01-20 17:10:20.364 32535 32535 E ErrorListener:         at org.matrix.androidsdk.rest.callback.RestAdapterCallback$1.onHttpError(RestAdapterCallback.java:149)
01-20 17:10:20.364 32535 32535 E ErrorListener:         at org.matrix.androidsdk.core.rest.DefaultRetrofit2ResponseHandler.handleResponse(DefaultRetrofit2ResponseHandler.java:32)
01-20 17:10:20.364 32535 32535 E ErrorListener:         at org.matrix.androidsdk.rest.callback.RestAdapterCallback.handleResponse(RestAdapterCallback.java:139)
01-20 17:10:20.364 32535 32535 E ErrorListener:         at org.matrix.androidsdk.rest.callback.RestAdapterCallback.onResponse(RestAdapterCallback.java:132)
01-20 17:10:20.364 32535 32535 E ErrorListener:         at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
01-20 17:10:20.364 32535 32535 E ErrorListener:         at android.os.Handler.handleCallback(Handler.java:873)
01-20 17:10:20.364 32535 32535 E ErrorListener:         at android.os.Handler.dispatchMessage(Handler.java:99)
01-20 17:10:20.364 32535 32535 E ErrorListener:         at android.os.Looper.loop(Looper.java:193)
01-20 17:10:20.364 32535 32535 E ErrorListener:         at android.app.ActivityThread.main(ActivityThread.java:6718)
01-20 17:10:20.364 32535 32535 E ErrorListener:         at java.lang.reflect.Method.invoke(Native Method)
01-20 17:10:20.364 32535 32535 E ErrorListener:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-20 17:10:20.364 32535 32535 E ErrorListener:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-20 17:10:20.367 32535 32535 E EventsThread: Sync V2 onUnexpectedError null
01-20 17:10:20.367 32535 32535 E EventsThread: org.matrix.androidsdk.core.model.HttpException
01-20 17:10:20.367 32535 32535 E EventsThread:  at org.matrix.androidsdk.rest.callback.RestAdapterCallback$1.onHttpError(RestAdapterCallback.java:149)
01-20 17:10:20.367 32535 32535 E EventsThread:  at org.matrix.androidsdk.core.rest.DefaultRetrofit2ResponseHandler.handleResponse(DefaultRetrofit2ResponseHandler.java:32)
01-20 17:10:20.367 32535 32535 E EventsThread:  at org.matrix.androidsdk.rest.callback.RestAdapterCallback.handleResponse(RestAdapterCallback.java:139)
01-20 17:10:20.367 32535 32535 E EventsThread:  at org.matrix.androidsdk.rest.callback.RestAdapterCallback.onResponse(RestAdapterCallback.java:132)
01-20 17:10:20.367 32535 32535 E EventsThread:  at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
01-20 17:10:20.367 32535 32535 E EventsThread:  at android.os.Handler.handleCallback(Handler.java:873)
01-20 17:10:20.367 32535 32535 E EventsThread:  at android.os.Handler.dispatchMessage(Handler.java:99)
01-20 17:10:20.367 32535 32535 E EventsThread:  at android.os.Looper.loop(Looper.java:193)
01-20 17:10:20.367 32535 32535 E EventsThread:  at android.app.ActivityThread.main(ActivityThread.java:6718)
01-20 17:10:20.367 32535 32535 E EventsThread:  at java.lang.reflect.Method.invoke(Native Method)
01-20 17:10:20.367 32535 32535 E EventsThread:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-20 17:10:20.367 32535 32535 E EventsThread:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-20 17:10:20.369 32535 32535 I EventsThread: Waiting a bit before retrying
```

I currently use riot-web (both web-hosted and electron) and riotx-android without difficulty. I've submitted rageshakes for both the play store version and the f-droid version. I haven't tried logging out of riotx and logging in again, since that's the only mobile client I have working right now. :wink:

I wasn't sure if this should be opened against riot-android or against matrix-android-sdk, and I'm happy to re-open it over there if that's more appropriate.

**Comment by logic** [comment]
This was a homeserver configuration error; while I think better reporting of failures like this back to the user would be worthwhile, I suspect there are other issues that already cover that (and the future is riotx anyway).
